var initialState = {
  isPlaying: false,
  tempo: 120,
  swing: 0,
  channels: [],
  samplePaths: [
    'static/samples/707_BD0.wav',
    'static/samples/707_BD1.wav',
    'static/samples/707_COW.wav',
    'static/samples/707_CRS.wav',
    'static/samples/707_HCP.wav',
    'static/samples/707_HHC.wav',
    'static/samples/707_HHO.wav',
    'static/samples/707_HT.wav',
    'static/samples/707_LT.wav',
    'static/samples/707_MT.wav',
    'static/samples/707_RID.wav',
    'static/samples/707_RIM.wav',
    'static/samples/707_SD0.wav',
    'static/samples/707_SD1.wav',
    'static/samples/707_TAM.wav',
    'static/samples/cabasa.wav',
    'static/samples/chh.wav',
    'static/samples/clap.wav',
    'static/samples/conga.wav',
    'static/samples/congal.wav',
    'static/samples/cowb.wav',
    'static/samples/crash.wav',
    'static/samples/hitom.wav',
    'static/samples/kick1.wav',
    'static/samples/kick2.wav',
    'static/samples/linn_bp.wav',
    'static/samples/lotom.wav',
    'static/samples/midtom.wav',
    'static/samples/ohh.wav',
    'static/samples/ride.wav',
    'static/samples/sd1.wav',
    'static/samples/sd2.wav',
    'static/samples/sst.wav',
    'static/samples/tamb.wav'
  ]
};

module.exports = initialState;
